name: CI

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --sdist -o dist
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
